title: Dynamic Content
extends@: default

form:
  fields:
    tabs:
      fields:
        content:
          fields:

            # content_section:
            #   ordering@: 3
            #   type: section
            #   title: Content Section
            #   underline: true
              
            #   fields:
            #     header.contents:
            #       style: vertical
            #       type: list
            #       fields:
            #         .img:
            #           type: pagemediaselect
            #           label: Image
            #         .title.translatable:
            #           type: text
            #           label: Title
            #           classes: 'translatable'
            #         .text.translatable:
            #           type: textarea
            #           label: Details
            #           classes: 'translatable'
            #           rows: 8

            no_hero_content_section:
              ordering@: 3
              type: section
              title: No Hero Content Section
              underline: true

              fields:
                header.no_hero_content.section_background_image:
                  type: pagemediaselect
                  label: Section Background Image
                  preview_images: true

                header.no_hero_content.title.translatable:
                  type: text
                  label: Title
                  classess: 'translatable'

                header.no_hero_content.subtitle.translatable:
                  type: text
                  label: Sub Title
                  classess: 'translatable'

                header.no_hero_content.description.translatable:
                  type: textarea
                  label: Description
                  classess: 'translatable'

                header.no_hero_content.button_text.translatable:
                  type: text
                  label: Button Text
                  classess: 'translatable'

                header.no_hero_content.image_for_desktop:
                    type: pagemediaselect
                    label: No Hero image for Desktop
                    preview_images: true
 
                header.no_hero_content.image_top_left:
                    type: pagemediaselect
                    label: No Hero image top left
                    preview_images: true

                header.no_hero_content.image_bottom_right:
                    type: pagemediaselect
                    label: No Hero image bottom right
                    preview_images: true


                header.footer_content.pricing.translatable:
                  type: text
                  label: Footer Pricing
                  classess: 'translatable'

                header.footer_content.footer_link_title1.translatable:
                  type: text
                  label: Footer link title one
                  classess: 'translatable'

                header.footer_content.footer_link_title2.translatable:
                  type: text
                  label: Footer link title two
                  classess: 'translatable'

                header.footer_content.footer_contact_title.translatable:
                  type: text
                  label: Footer contact title 
                  classess: 'translatable'

